### PR TITLE
Corrects issues with linting output

### LINKED ISSUE #1: HI, This plugin does not seem to work properly, Please check this link below
https://github.com/godotengine/godot-vscode-plugin/issues/390

### LINKED ISSUE #2: Errors during linting process.
When running this on files with multiple intentional errors, the first line of all .gd files is an error-line with the following hover over:
image
sometimes it's quite a few errors stacked depending on the amount of actual errors gdlint finds:
image

The console looks like this:
image

Running gdlint from the command line results in expected output of actual errors/warnings to the console.

GDToolkit v 3.4.0
Godot v3.5.1
VSCode - Oct 2022

### PR DESCRIPTION
**Pull request by EddieDover**
Fixes #1
Fixes #2

### CODE REVIEW

**Comment by EddieDover** [comment]
It's been two years since this project has had an update and I'm very tempted to declare it unmaintained.  If this PR gets no traction within the next few days, I'll fork and create a new VSCode Extension with the improvements.

**Comment by kuhnchris** [comment]
Since I am not using the extension anymore (at least at this moment), feel free to publish a fork of it, if you want. I added your PR regardless, I quickly glanced over it and it seemed valid. If you want I can transfer you the ownership of the package, just let me know :+1:

**Comment by EddieDover** [comment]
Hey @kuhnchris, thank you for such a prompt response. I assumed you might not have been using the plugin anymore but I do want to thank you for creating it in the first place. Not having proper linting/formatting for GDS in VSC was really irritating me and yours was the only plugin that seemed to want to address both issues at the same time.

If you are comfortable transferring ownership, I will not complain. Just let me know if you need anything from me.

**Comment by kuhnchris** [comment]
No problem! I was also confused about the missing lint and code check, hence this plugin came to life. At some point I did give up, as the built-in editor is far quicker, especially with intellisense and the built-in help - it does have it's nitpicks, but I kind of just went with it at this point.
I'd love to transfer the ownership, but you already have a fork of the same name, if you can remove your fork I can transfer it to you - let me know! 
To publish on the marketplace you probabbly need an account aswell, not sure how I can transfer there, but I'll check and let you know asap.

Cheers,
Chris

**Comment by EddieDover** [comment]
@kuhnchris I've deleted my fork.  If you can't transfer the package from the marketplace then give me an hour or so after you transfer the repo and I can publish my own package then we can mark yours as deprecated and point people to the new one.

**Comment by kuhnchris** [comment]
You already received the repo, as you already saw and started on the new branch (thanks by the way :-) ) - the extension itself on the marketplace cannot be removed from my side, as I do not find the account it was registered with - I tried to restore a 2nd account but that may take a bit. If you are in a hurry, feel free to deprecate my "old" version :-)

Thanks for taking care of this,
Chris

**Comment by MysterieCatGames** [comment]
Chris,

There's absolutely no rush on this. I don't think I can properly deprecate the old version anyway since I believe we need the actual marketplace account holder to do it.  In fact, it's something I've never really delt with before, but I believe there is also a way you can flag a different plugin as a 'successor' and the system will offer current users the ability to auto migrate from the deprecated plugin.  Interesting stuff!  When you get your account recovered, please let me know what you learn about the process.

I'll work on getting the new plugin published today and report back. I was also attempting some integration testing with Mocha last night but it did NOT play nice with the child_process, so I'm not 100% sure it will be possible, which makes me a little sad.

**Comment by EddieDover** [comment]
Chris,

There's absolutely no rush on this. I don't think I can properly deprecate the old version anyway since I believe we need the actual marketplace account holder to do it. In fact, it's something I've never really delt with before, but I believe there is also a way you can flag a different plugin as a 'successor' and the system will offer current users the ability to auto migrate from the deprecated plugin. Interesting stuff! When you get your account recovered, please let me know what you learn about the process.

I'll work on getting the new plugin published today and report back. I was also attempting some integration testing with Mocha last night but it did NOT play nice with the child_process, so I'm not 100% sure it will be possible, which makes me a little sad.

**Comment by EddieDover** [comment]
And the package is in the marketplace!

https://marketplace.visualstudio.com/items?itemName=EddieDover.gdscript-formatter-linter

**Pull request merged**
